### ISSUE TITLE
ERROR [tesla-sentry-viewer-frontend builder 5/5] RUN yarn build

### ISSUE THREAD

**Issue by forgottenruntime** [rufogongora/teslacamviewer#19]
=> ERROR [tesla-sentry-viewer-frontend builder 5/5] RUN yarn build                                                                                            6.3s
------                                                                                                                                                              
 > [tesla-sentry-viewer-frontend builder 5/5] RUN yarn build:                                                                                                       
2.933 yarn run v1.22.19                                                                                                                                             
2.943 warning package.json: No license field                                                                                                                        
2.954 $ vue-tsc --noEmit && vite build                                                                                                                              
4.860 src/views/HomeView.vue(2,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.                         
4.860 src/components/icons/IconCommunity.vue(2,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/views/HomeView.vue(3,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/views/ClipsView.vue(6,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/App.vue(6,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/components/icons/IconSupport.vue(3,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/components/icons/IconCommunity.vue(3,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/components/icons/IconDocumentation.vue(3,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/components/icons/IconEcosystem.vue(3,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/App.vue(7,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/views/ClipsView.vue(7,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/App.vue(8,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/components/icons/IconTooling.vue(3,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.860 src/components/icons/IconTooling.vue(14,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.861 src/components/ClipsList.vue(29,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.861 src/components/ClipsList.vue(35,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.861 src/components/ClipsList.vue(36,9): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.861 src/components/ClipsList.vue(40,9): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.861 src/components/ClipsList.vue(41,11): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.861 src/views/SingleClipView.vue(156,5): error TS7023: 'currentVideoTime' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
4.861 src/views/SingleClipView.vue(166,11): error TS7022: 'newDate' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
4.861 src/views/SingleClipView.vue(166,50): error TS2339: Property 'videoTime' does not exist on type '{ currentVideoTime(): any; }'.
4.862 src/views/SingleClipView.vue(186,3): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(187,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(189,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(190,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(191,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(193,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(194,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(196,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(197,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(198,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(199,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(200,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(202,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(203,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(208,9): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.862 src/views/SingleClipView.vue(214,11): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
4.895 error Command failed with exit code 2.
4.895 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 2

**Comment by SpeedlimitsB** [comment]
i am not certain if you can help me with this :-)
