### ISSUE TITLE
Videos no longer show [BUG]

### ISSUE THREAD

**Issue by Dulanic** [rufogongora/teslacamviewer#9]
Hello,

So I appreciate the no login change you made for me :) 2 Follow up questions. 

1.  How do I disable the login? 
2. What happened to my videos?  hehe I show the docker mount where there are some videos... they used to show, but they don't after the most recent update.

![image](https://user-images.githubusercontent.com/2948206/196967513-b3c86202-b539-4a6a-a80f-0208e771690d.png)
![image](https://user-images.githubusercontent.com/2948206/196967664-1fcf341a-7341-4dd4-909b-a6db521dd03b.png)

Docker log:

```
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {72b89066-0609-4ae2-88f8-e12251a3d321} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
```

**Comment by rufogongora** [comment]
Taking a look at this now, but in order to disable authorization all you need to do is set the environment variable
`- authorization enabled=false`

**Comment by rufogongora** [comment]
@Dulanic, would you be so kind as to send me the response from this network request? 

![image](https://user-images.githubusercontent.com/6101004/196979781-ca64ce3f-8422-4139-9200-31942e68e27d.png)

You can bring up the network tab on the google chrome/firefox dev tools by hitting F12 on your keyboard and then finding the `teslaFolder` request

I have pulled the last docker image and it seems to work on both my windows/linux machines, so I'm wondering if there's some read permissions for your docker container?

And as a side comment, I'm reworking all of this so it'll be way more optimized and work on other browsers as well, should take me around a week :)

**Comment by Dulanic** [comment]
Thanks! I missed that env variable part :)

**Comment by Dulanic** [comment]
I am seeing no response at all. I wonder if It's my reverse proxy? It would be odd since it works before but let me try direct....

![image](https://user-images.githubusercontent.com/2948206/197003749-38ced078-9fcb-4012-9d71-c58207e5167d.png)
![image](https://user-images.githubusercontent.com/2948206/197003790-578205c0-8bc3-42f8-bc15-7da81b38f080.png)

**Comment by Dulanic** [comment]
Yeah still nothing even using local ip instead of reverse proxy... Also no response information just [].

![image](https://user-images.githubusercontent.com/2948206/197004341-45f28a90-973b-4718-b94b-33145d198973.png)

**Comment by Dulanic** [comment]
If it helps, I just opened up the url since there is no videos anyways. https://teslacam.dulanic.com

**Comment by rufogongora** [comment]
thanks for all the useful info, the fact that the response is just an empty array `[]` means that the controller and the response is working, it's just not finding any "valid" folders, I'm looking at the code and it required that the `event.json` file is present on all of the clip folders, is this file present on all of the clip folders?

**Comment by Dulanic** [comment]
That may be the reason then. I don't have the .json for old footage that I
am storing. Is that new? That requirement.

**Comment by rufogongora** [comment]
I think it's always been, but don't worry, that file is only used to handle stuff like the location and all that, what I'll do is make it optional to have the file, it just won't display map data.

I'll keep you posted once it's fixed.
Sorry if there's no versioning on the docker image, I'm still figuring out how to do the publishing since it's my first time 😅

**Comment by Dulanic** [comment]
All good man! Thanks! I may have "dropped" those json files when I moved them to being stored on google drive and just forgot to copy the json files. I appreciate it!

**Comment by Dulanic** [comment]
Oh if you want to see an example of versioning/tagging.... this was my first attempt and I think it mostly works... I just tag /w git and it works.... I think! I'm kind of new to that part too.

https://github.com/Dulanic/docker-caddy/

**Comment by rufogongora** [comment]
I merged a fix but the changes on the folder structure broke the image, I will let you know once the Dockerfile is fixed :)

**Comment by rufogongora** [comment]
also, I just realized that tagging is done automatically based on the branch name, duh... no more broken releases from now on lol

**Comment by rufogongora** [comment]
Issue is now fixed! let me know how it goes!

**Comment by Dulanic** [comment]
Docker container seems totally broken now. 

```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'teslacamviewer.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

**Comment by rufogongora** [comment]
This was due to an issue with me renaming the .csproj but I fixed it with this commit

https://github.com/rufogongora/teslacamviewer/commit/7a0b288750f220872bafcecc1b222bbf40a8e515

Have you ran `docker-compose pull` on the :main branch?

**Comment by Dulanic** [comment]
Thanks! Looks better!

**Comment by Dulanic** [comment]
Oh I already closed this, but I do have no thumbnals. I wont reopen since thats not what this was for and im not sue if this is due to no .json file.

![image](https://user-images.githubusercontent.com/2948206/197074837-350b2ee6-043e-49c5-b333-6bb1e9a92610.png)

**Comment by rufogongora** [comment]
but you do have the file right? well I'll package this as part of the refactoring I'm doing for optimization so it won't have to a directory scan every time the page loads, I'm halfway through with that change

**Comment by Dulanic** [comment]
OK, so I think I see why.... it shows the videos now but nothing plays. I can play them directly myself, but not through this. Prob due to not being firefox....

**Comment by rufogongora** [comment]
yep unfortunately this is due to a codec issue with google chrome, apparently it does not support the one that tesla uses.
for now you'll have to use firefox (I haven't tested any other browser other than chrome/firefox).

The good thing is that's why I'm refactoring the directory scanning, I'll be using ffmpeg to decode the files (and maybe even merge them into a single file) so that playback works on any browser

**Comment by Dulanic** [comment]
Sounds good! Was going to say Ill convert /w ffmpeg, but if you're doing that, Ill skip. Thanks!
